// AUTO-GENERATED by scripts/gen-backgrounds.mjs — do not edit by hand.
// Regenerate after adding files to /public/backgrounds:  npm run gen:backgrounds
export const BACKGROUNDS: string[] = [
  "/backgrounds/ring-1.jpg",
  "/backgrounds/ring-2.jpg",
  "/backgrounds/ring-3.jpg",
  "/backgrounds/ring-4.jpg"
];
