// ── Promotion registry ─────────────────────────────────────────────────────
// Single source of truth for the organisations we surface. Keeps branding
// consistent everywhere (event headers, cards, schedules) instead of scattering
// per-promotion strings/colours across components.
//
// Adding a real logo: drop a transparent PNG/SVG at
//   public/promotions/<slug>.svg   (or .png)
// and set `logo: "/promotions/<slug>.svg"` on the entry. Until then the
// <PromotionLogo> component renders a branded monogram fallback, so every event
// still gets a consistent mark beside its title — no broken images, no blank
// space. `brand` is the org's primary colour; `mark` is the short monogram.

export interface Promotion {
  slug: string;
  name: string;
  /** Short monogram for the fallback badge (2–4 chars). */
  mark: string;
  /** Primary brand colour (hex). */
  brand: string;
  /** Local transparent logo, once placed under public/promotions/. */
  logo?: string;
  /** Lower-case phrases that identify this promotion in a free-text field. */
  aliases: string[];
}

// Order matters: the resolver takes the FIRST alias match, so put more specific
// promotions (e.g. "road to ufc") before broader ones ("ufc").
//
// `logo` points at an ORIGINAL brand-coloured mark generated by
// scripts/gen-promotion-logos.mjs — regenerate after editing this list. To use a
// promotion's official licensed artwork, drop it at the same path (same slug)
// and it overrides ours automatically; no code change needed.
export const PROMOTIONS: Promotion[] = [
  { slug: "road-to-ufc", name: "Road to UFC", mark: "RTU", brand: "#d20a0a", logo: "/promotions/road-to-ufc.svg", aliases: ["road to ufc"] },
  { slug: "dwcs", name: "Dana White's Contender Series", mark: "DWCS", brand: "#d20a0a", logo: "/promotions/dwcs.svg", aliases: ["contender series", "dana white", "dwcs"] },
  { slug: "ufc", name: "UFC", mark: "UFC", brand: "#d20a0a", logo: "/promotions/ufc.svg", aliases: ["ufc", "ultimate fighting"] },
  { slug: "one", name: "ONE Championship", mark: "ONE", brand: "#e8112d", logo: "/promotions/one.svg", aliases: ["one championship", "one fight night", "one friday fights", "onefc", "one fc"] },
  { slug: "pfl", name: "PFL", mark: "PFL", brand: "#e4002b", logo: "/promotions/pfl.svg", aliases: ["pfl", "professional fighters league"] },
  { slug: "bellator", name: "Bellator", mark: "BEL", brand: "#c8a24a", logo: "/promotions/bellator.svg", aliases: ["bellator"] },
  { slug: "bkfc", name: "BKFC", mark: "BKFC", brand: "#c8102e", logo: "/promotions/bkfc.svg", aliases: ["bkfc", "bare knuckle", "bare-knuckle"] },
  { slug: "glory", name: "GLORY", mark: "GLO", brand: "#e2001a", logo: "/promotions/glory.svg", aliases: ["glory kickboxing", "glory"] },
  { slug: "rizin", name: "RIZIN", mark: "RIZ", brand: "#c9a227", logo: "/promotions/rizin.svg", aliases: ["rizin"] },
  { slug: "ksw", name: "KSW", mark: "KSW", brand: "#d0021b", logo: "/promotions/ksw.svg", aliases: ["ksw", "konfrontacja"] },
  { slug: "oktagon", name: "Oktagon MMA", mark: "OKT", brand: "#00a3e0", logo: "/promotions/oktagon.svg", aliases: ["oktagon"] },
  { slug: "cage-warriors", name: "Cage Warriors", mark: "CW", brand: "#d10a11", logo: "/promotions/cage-warriors.svg", aliases: ["cage warriors"] },
  { slug: "lfa", name: "LFA", mark: "LFA", brand: "#b11116", logo: "/promotions/lfa.svg", aliases: ["lfa", "legacy fighting", "legacy fc"] },
  { slug: "eternal-mma", name: "Eternal MMA", mark: "ETL", brand: "#1e88e5", logo: "/promotions/eternal-mma.svg", aliases: ["eternal mma"] },
  { slug: "hex", name: "Hex Fight Series", mark: "HEX", brand: "#7b1fa2", logo: "/promotions/hex.svg", aliases: ["hex fight", "hex "] },
  { slug: "cffc", name: "CFFC", mark: "CFFC", brand: "#c0161d", logo: "/promotions/cffc.svg", aliases: ["cffc", "cage fury"] },
  { slug: "invicta", name: "Invicta FC", mark: "INV", brand: "#e91e63", logo: "/promotions/invicta.svg", aliases: ["invicta"] },
  { slug: "karate-combat", name: "Karate Combat", mark: "KC", brand: "#00b4d8", logo: "/promotions/karate-combat.svg", aliases: ["karate combat"] },
  { slug: "adcc", name: "ADCC", mark: "ADCC", brand: "#2e7d32", logo: "/promotions/adcc.svg", aliases: ["adcc", "submission fighting"] },
];

const FALLBACK: Promotion = {
  slug: "combat",
  name: "Fight Card",
  mark: "★",
  brand: "#8a8f98",
  aliases: [],
};

/**
 * Resolve a free-text promotion string to a registry entry. Never returns null
 * — an unknown promotion still gets a neutral fallback mark so the UI stays
 * consistent. When `promotion` is a plain unknown name we keep its display text
 * but use a generic mark derived from the name's initials.
 */
export function resolvePromotion(promotion?: string | null): Promotion {
  const q = (promotion ?? "").toLowerCase().trim();
  if (!q) return FALLBACK;
  for (const p of PROMOTIONS) {
    if (p.aliases.some((a) => q.includes(a))) return p;
  }
  // Unknown promotion: keep its real name, derive a monogram from its initials.
  const mark = promotion!
    .split(/\s+/)
    .map((w) => w[0])
    .join("")
    .slice(0, 4)
    .toUpperCase();
  return { ...FALLBACK, name: promotion!, mark: mark || FALLBACK.mark };
}
