import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { EmptyState } from "@/components/ui/empty-state";
import { ArrowRight, Play, Trophy, Mic, TrendingUp, Megaphone, Scale, Swords, BarChart3, Siren, Flame, Newspaper, type LucideIcon } from "lucide-react";

// Clean monochrome section icons — one per coverage group key (no emoji).
const COVERAGE_ICON: Record<string, LucideIcon> = {
  highlights: Play,
  result: Trophy,
  interview: Mic,
  next: TrendingUp,
  presser: Megaphone,
  weighin: Scale,
  faceoff: Swords,
  predictions: BarChart3,
  updates: Siren,
  reactions: Flame,
  news: Newspaper,
};
import { getEvent, getOddsForFight } from "@/lib/repo";
import { SITE } from "@/lib/config";
import { marketProbability, type MarketProb } from "@/lib/market";
import { safeNewsCover } from "@/lib/media-safe";
import type { Article, Fight } from "@/lib/types";
import { formatDate } from "@/lib/utils";
import { orderFights, groupCoverage, winningCorner } from "@/lib/event-format";
import { getEventEnrichment } from "@/lib/events/enrichment";
import { VideoRail } from "@/components/feed/video-rail";
import { resolvePromotion } from "@/lib/promotions";
import { classifyCard, cardStateCopy, promotionCoveredBySlug } from "@/lib/events/card-completeness";
import { getCurrentUser } from "@/lib/auth";
import { isFollowingPromotion, isFollowingEvent } from "@/lib/follows";
import { getEventPickSummary } from "@/lib/profile-stats";
import { getCrowdForFightIds, getMyPicksForFightIds, type CrowdRead, type MyPick } from "@/lib/picks";
import { getRoomSummaries } from "@/lib/community/rooms";
import { prisma } from "@/lib/db";
import { ResultReveal } from "@/components/event/result-reveal";
import { TheRoom } from "@/components/event/the-room";
import { getEventRoom } from "@/lib/identity/event-room";
import { EventHeader } from "@/components/event/event-header";
import { EventSchedule } from "@/components/event/event-schedule";
import { resultCoverage } from "@/lib/events/result-coverage";
import { HeadlineMatchup } from "@/components/event/headline-matchup";
import { EventScrollSpy, type SpySection } from "@/components/event/event-scroll-spy";
import { segmentCard, estimateBoutTimes, currentBoutId, boutProgress } from "@/lib/card-segments";
import { FightRow } from "@/components/event/fight-row";
import { BoutPick } from "@/components/predictions/bout-pick";
import { picksLocked, pickStatus, STATUS_PRESENTATION } from "@/lib/intelligence/pick-status";
import { FightModule } from "@/components/fight/fight-module";
import { CollapsibleFights } from "@/components/event/collapsible-fights";
import { EventGeneralRoom } from "@/components/event/event-general-room";
import { WhenVisible } from "@/components/when-visible";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const e = await getEvent(slug);
  if (!e) return {};

  // CANONICAL. Without `alternates.canonical` Next falls back to metadataBase,
  // so every event page declared the site ROOT as its canonical URL — hundreds
  // of distinct pages competing under one address, telling search engines they
  // are all the same document.
  //
  // The share card is generated by ./opengraph-image (event name, promotion
  // mark, date, venue). `images` is deliberately NOT set here: setting it
  // shadows that route, which is the mistake the fighter page documents.
  const when = formatDate(e.date);
  const where = [e.venue, e.city, e.country].filter(Boolean).join(", ");
  // Composed conditionally — a card with no venue must not render "  · , , ".
  const facts = [e.promotion, when, where].filter(Boolean).join(" · ");
  const title = e.promotion && !e.name.toLowerCase().includes(e.promotion.toLowerCase())
    ? `${e.promotion}: ${e.name}`
    : e.name;
  const description = `${e.name}${facts ? ` — ${facts}.` : "."} Full fight card, results, coverage and predictions on Combat Reviews.`;

  return {
    title,
    description,
    alternates: { canonical: `/events/${slug}` },
    openGraph: {
      title,
      description,
      type: "article",
      url: `${SITE.url}/events/${slug}`,
    },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function EventPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const event = await getEvent(slug);
  if (!event) notFound();

  // Read in the order fans expect: main event, co-main, titles, then the
  // official undercard order.
  const fights = orderFights(event.fights);
  const headline = fights.find((f) => f.mainEvent) ?? fights[0];

  // Result completeness, from the ONE shared definition. Passed to the schedule
  // banner so it cannot contradict the card rendered below it — that banner used to
  // read "Results pending · sources are checked hourly" directly above a bout showing
  // "TKO Round 7", because it derived its status from event.status and had no idea
  // whether any result had landed.
  //
  // The repo now carries the harvest bookkeeping (resultAttempts /
  // resultCoveragePct), so this resolves the TERMINAL state too. That matters
  // for the reader, not just the harvester: a card whose only source has stopped
  // yielding bouts used to sit on "Results updating — sources are checked
  // hourly" forever, promising an update that was never coming.
  const coverage = resultCoverage({
    total: fights.length,
    decided: fights.filter((f) => f.result !== "SCHEDULED").length,
    attempts: event.resultAttempts ?? 0,
    lastCoveragePct: event.resultCoveragePct ?? null,
  });

  // The card as a fan watches it: broadcast blocks in run order, each bout with
  // an estimated walkout time and where it sits in the night. `derived` is true
  // when no provider gave us blocks — every time is then labelled an estimate.
  const { derived: segmentsDerived, blocks } = segmentCard(fights);
  const eventDate = new Date(event.date);
  const boutTimes = estimateBoutTimes(blocks, eventDate);
  const liveBoutId = currentBoutId(blocks, event.status);

  // Resolve the viewer once up front (cache-deduped) and reuse it below.
  const viewer = await getCurrentUser();

  // Two independent reads run concurrently — page latency is the slower of them,
  // not their sum.
  //  - odds: real market-implied probability per bout, from the licensed feed.
  //  - enrichment: the ONE event-intelligence object — ranked coverage, matched
  //    videos, the verified result and the hero selections — composed by
  //    getEventEnrichment so this page (and fighter/promotion/search later) never
  //    re-derive the taxonomy. See lib/events/enrichment.ts.
  const [oddsList, enrichment] = await Promise.all([
    Promise.all(fights.map((f) => getOddsForFight(f.slug))),
    getEventEnrichment(event, fights, { viewerId: viewer?.id ?? null }),
  ]);
  const marketBySlug = new Map<string, MarketProb | null>(
    fights.map((f, i) => [f.slug, marketProbability(oddsList[i])]),
  );

  // Promotion personality: every event uses the SAME layout, but its promotion's
  // brand colour flows through the hero/schedule/main-event accents via --accent.
  const resolvedPromo = resolvePromotion(event.promotion);
  const accent = resolvedPromo.brand;
  // "combat" is the neutral fallback for an unknown/"Various" promotion — not an
  // organisation, and never something we can claim coverage for.
  const promoSlug = resolvedPromo.slug === "combat" ? null : resolvedPromo.slug;

  // Is the viewer following this promotion? (drives the header follow button)
  const [promotionFollowing, eventFollowing] = viewer
    ? await Promise.all([
        event.promotion ? isFollowingPromotion(viewer.id, event.promotion) : Promise.resolve(false),
        isFollowingEvent(viewer.id, event.id),
      ])
    : [false, false];

  // Crowd predictions for the whole card in TWO queries (batched — no N+1): the
  // aggregate read for everyone, and this viewer's own picks. Same store and the
  // same /api/fights/[slug]/pick write BoutPick uses on /predictions — one source
  // of truth, not a parallel prediction system.
  const fightIds = fights.map((f) => f.id);
  const [crowdByFightId, myPicksByFightId, roomsByFightId] = await Promise.all([
    getCrowdForFightIds(fightIds),
    viewer ? getMyPicksForFightIds(viewer.id, fightIds) : Promise.resolve(new Map<string, MyPick>()),
    // Battle Rooms: the room counters + the viewer's battle per bout, for the WHOLE
    // card in three queries. Nothing is provisioned and no discussion is fetched
    // until a reader opens an arena — that work belongs to /api/fights/[slug]/room.
    getRoomSummaries(fightIds, viewer?.id),
  ]);

  // Result reveal — only on a completed event, only for a viewer who made picks.
  const isCompleted = event.status === "COMPLETED";
  const [pickSummary, viewerStreak] = viewer && isCompleted
    ? await Promise.all([
        getEventPickSummary(viewer.id, fights.map((f) => f.id)),
        prisma.user.findUnique({ where: { id: viewer.id }, select: { pickStreak: true } }).then((u) => u?.pickStreak ?? 0),
      ])
    : [null, 0];

  // The Room — the community's call on the headline bout. Shown on a completed
  // event for everyone (not just pickers): it is social proof, not a personal
  // result. Null when the crowd was below quorum or the bout was a draw/NC.
  const room = isCompleted && headline ? await getEventRoom(headline.id) : null;

  // Did a PROVIDER hand us this event? Only asked when there are no bouts, because
  // that is the only case where the answer changes what the reader is told — and it
  // is the difference between "the promotion hasn't announced it" and "a source gave
  // us this event and we lost its card", which is our bug to own.
  const hasProviderProvenance =
    fights.length === 0 &&
    (await prisma.eventExternalId.count({ where: { eventId: event.id } }).catch(() => 0)) > 0;

  // One scroll: card → card talk → coverage. There is no separate Predictions
  // section — a bout's prediction, battle and discussion live inside that bout's
  // module, because that is the scope a fan actually thinks in. "Card talk" is
  // the event-wide room for everything that belongs to no single bout.
  // The section list is DERIVED by the enrichment engine (navigation.sections),
  // not recomputed here: a "Coverage" anchor exists only when enrichment actually
  // found coverage or videos, and that rule now lives in one place for every
  // surface that needs it.
  const spy: SpySection[] = enrichment.navigation.sections;

  // WHY the card is empty, decided once. `covered` asks the ingestion registry
  // whether any ENABLED source reaches this promotion — a promotion we deliberately
  // do not ingest must say so rather than implying the card is merely late.
  // `hasProviderProvenance` distinguishes our failure from the promotion's silence: a
  // source that handed us the event should have handed us its bouts.
  const cardState = classifyCard({
    boutCount: fights.length,
    status: event.status,
    date: new Date(event.date),
    promotionSlug: promoSlug,
    covered: promotionCoveredBySlug(promoSlug),
    // Provenance = a provider handed us this event. If it did and there are no
    // bouts, the card was lost on our side.
    hasProviderProvenance: hasProviderProvenance,
  });
  const cardCopy = cardStateCopy(cardState);

  return (
    <div style={{ "--accent": accent } as React.CSSProperties}>
      {/* Hero → Schedule (when) → Headline (the fight) — the top of the funnel. */}
      <EventHeader
        event={event}
        promotionFollowing={promotionFollowing}
        eventFollowing={eventFollowing}
        boutCount={fights.length}
      />
      {pickSummary && (
        <ResultReveal
          summary={pickSummary}
          streak={viewerStreak}
          scorecardHref={viewer?.username ? `/u/${viewer.username}/card/${event.slug}` : null}
        />
      )}
      {room && <TheRoom room={room} />}
      <EventSchedule
        date={event.date}
        status={event.status}
        coverage={coverage}
        estimated={segmentsDerived}
        blocks={blocks.map((b) => ({
          key: b.meta.key,
          label: b.meta.label,
          startsAt: new Date(eventDate.getTime() - b.meta.offsetMinutes * 60_000).toISOString(),
          bouts: b.fights.length,
        }))}
      />
      {headline && <HeadlineMatchup fight={headline} market={marketBySlug.get(headline.slug) ?? null} />}

      {/* Sticky scroll-spy, then the sections continuously below it. */}
      <EventScrollSpy sections={spy} />

      {/* The card IS the product surface: every bout is an independent module
          carrying its own prediction, battle and discussion. */}
      <ScrollSection id="card" title="Fight card" seam={false}>
        {fights.length === 0 ? (
          /* AN EMPTY CARD IS SEVERAL DIFFERENT STATES, not one.
             "The promotion hasn't announced it", "we don't cover this promotion" and
             "our importer dropped the card" are three different truths with three
             different next actions — and rendering the same sentence for all of them
             (or nothing at all, as this did) makes our own bug look like the
             promotion's silence. classifyCard decides which one applies; the copy
             never blames the promotion for our gap or vice versa. */
          <EmptyState
            compact
            icon={<Swords className="size-5" />}
            title={cardCopy.title}
            body={cardCopy.body}
            action={cardCopy.offerFollow ? { href: "#top", label: "Follow this event" } : undefined}
          />
        ) : (
        <>
        {/* Said ONCE, above the card, instead of under all twelve bouts.
            "Make your call — earn points if it lands. Skill, not betting." was
            correct copy in the wrong place: repeated per bout it became the
            single largest block of text on the page, and the sentence that
            matters legally is the one a reader has stopped reading. */}
        <p className="mb-3 flex items-center gap-1.5 text-[0.7rem] text-fog">
          <Swords className="size-3.5 shrink-0 text-blood-400" />
          Tap a corner to call each bout — correct calls earn points. Skill, not betting.
        </p>
        {/* Compressed: the top bouts (main event + co-main + one) render; the
            rest tuck behind a "View N more predictions" toggle so a reader reaches
            the card talk + coverage without scrolling past every bout. */}
        <CollapsibleFights initialVisible={3}>
          {blocks.flatMap((block) => block.fights).map((f) => (
                  <FightModule
                    key={f.id}
                    fightSlug={f.slug}
                    summary={roomsByFightId.get(f.id) ?? { voices: 0, battle: null }}
                    header={
                      <FightRow
                        fight={f}
                        index={fights.indexOf(f)}
                        market={marketBySlug.get(f.slug) ?? null}
                        estimatedAt={boutTimes.get(f.id)?.toISOString() ?? null}
                        estimated={segmentsDerived}
                        progress={boutProgress(f, f.id === liveBoutId)}
                      />
                    }
                    pick={
                      <BoutPrediction
                        fight={f}
                        crowd={crowdByFightId.get(f.id) ?? { red: 0, blue: 0, total: 0 }}
                        myPick={myPicksByFightId.get(f.id) ?? null}
                        market={marketBySlug.get(f.slug) ?? null}
                        eventDate={event.date}
                      />
                    }
                  />
          ))}
        </CollapsibleFights>
        </>
        )}
      </ScrollSection>

      {/* Card-wide talk. Provisioned only when the reader reaches it, so the
          write stays off every page load. */}
      <ScrollSection id="card-talk" title="Card talk">
        <WhenVisible placeholder={<RoomSkeleton />}>
          <EventGeneralRoom slug={event.slug} />
        </WhenVisible>
      </ScrollSection>

      {(enrichment.coverage.length > 0 || enrichment.videos.length > 0) && (
        <ScrollSection id="coverage" title="Related coverage">
          {/* Video sits INSIDE the coverage section rather than claiming a
              scroll-spy section of its own: it is the same job as the articles
              below it — what else there is to consume about this card. Each panel
              guards itself so the section shows whenever EITHER exists (matching
              the scroll-spy badge, which was previously reachable-but-empty when a
              card had videos but no articles). */}
          {enrichment.videos.length > 0 && (
            <VideoRail videos={enrichment.videos} title="Watch" moreHref="/clips" />
          )}
          {enrichment.coverage.length > 0 && <CoveragePanel articles={enrichment.coverage} />}
        </ScrollSection>
      )}

      {/* Tail space so the last section can scroll clear of the sticky rail and
          the bottom tab bar — no abrupt end to the document. */}
      <div className="h-16" aria-hidden />
    </div>
  );
}

/** Space-holding skeleton while a room mounts — no words, no spinner, no mention
 *  of loading; it simply reads as the conversation settling in. */
function RoomSkeleton() {
  return (
    <div className="mx-auto max-w-3xl space-y-3" aria-hidden>
      <div className="h-11 rounded-xl bg-ink-800/50" />
      <div className="h-24 rounded-xl bg-ink-900/70 ring-1 ring-ink-800/60" />
      <div className="ml-6 h-16 rounded-xl bg-ink-900/50 ring-1 ring-ink-800/50" />
    </div>
  );
}

/**
 * One section of the single-scroll event page. Centralises the rhythm so every
 * section breathes identically: consistent padding, a hairline seam (softer than
 * a hard rule) between sections, a quiet eyebrow title, `scroll-mt` so the sticky
 * rail never covers the heading on a jump, and a scroll-driven reveal as it
 * arrives. `id` is the scroll-spy anchor.
 */
function ScrollSection({
  id,
  title,
  seam = true,
  children,
}: {
  id: string;
  title: string;
  seam?: boolean;
  children: React.ReactNode;
}) {
  return (
    <section
      id={id}
      className={`reveal scroll-mt-16 px-4 py-8 ${seam ? "border-t border-ink-800/50" : ""}`}
    >
      <h2 className="mb-4 font-display text-sm font-bold uppercase tracking-[0.18em] text-fog">{title}</h2>
      {children}
    </section>
  );
}

/**
 * The prediction slot inside a bout's module. A scheduled bout renders the real
 * crowd-pick control (BoutPick — same component and backend everywhere); a decided
 * bout collapses to its outcome and how the crowd called it. The battle and the
 * discussion that hang off this prediction live one block below, in the arena.
 */
function BoutPrediction({ fight, crowd, myPick, market, eventDate }: { fight: Fight; crowd: CrowdRead; myPick: MyPick | null; market: MarketProb | null; eventDate: string }) {
  if (fight.result === "SCHEDULED") {
    // The card may have STARTED without a result being ingested yet. Picks are
    // closed at first bell (castPick enforces it server-side), so the control must
    // render locked and say what it is waiting for — otherwise a call made before
    // the bell reads as a live, open prediction for as long as the result is missing.
    const locked = picksLocked(eventDate);
    const status = pickStatus({ correct: null }, fight);
    return (
      <BoutPick
        fightSlug={fight.slug}
        redName={fight.red.name}
        blueName={fight.blue.name}
        initialCrowd={crowd}
        initialPick={myPick}
        marketRedP={market?.redP ?? null}
        locked={locked}
        lockedNote={locked ? STATUS_PRESENTATION[status].detail : undefined}
        // Compact on the card: this control repeats once per bout, and the full
        // variant's headings and explainer copy are correct once and noise
        // twelve times. The card states "Skill, not betting" ONCE, above the
        // first bout — see the card header — rather than under every one.
        variant="compact"
      />
    );
  }

  const won = winningCorner(fight);
  const winner = won === "red" ? fight.red : won === "blue" ? fight.blue : null;
  const crowdRight = won === "red" ? crowd.red : won === "blue" ? crowd.blue : 0;
  const pct = crowd.total ? Math.round((crowdRight / crowd.total) * 100) : 0;
  return (
    <div className="card-surface pred-card p-4">
      <div className="mb-2 flex items-center justify-between text-sm font-semibold text-chalk">
        <span className="truncate">{fight.red.name}</span>
        <span className="px-2 text-xs text-fog">vs</span>
        <span className="truncate text-right">{fight.blue.name}</span>
      </div>
      <div className="rounded-lg bg-ink-800 px-3 py-2 text-sm">
        {winner ? (
          <p className="text-chalk">
            <span className="font-semibold text-blood-300">{winner.name}</span>{" "}
            <span className="text-fog">
              def.{fight.method ? ` · ${fight.method}${fight.roundEnded ? ` R${fight.roundEnded}` : ""}` : ""}
            </span>
          </p>
        ) : (
          <p className="text-mist">{fight.result === "DRAW" ? "Draw" : fight.result === "NO_CONTEST" ? "No contest" : "Result pending"}</p>
        )}
      </div>
      {crowd.total > 0 && winner && (
        <p className="mt-2 text-xs text-fog">
          <span className="font-semibold text-chalk">{pct}%</span> of {crowd.total.toLocaleString()} picks called it.
        </p>
      )}
    </div>
  );
}

// ── Coverage relevance ────────────────────────────────────────────────────
// Promotion → the title phrases that signal a story is about that promotion.
// (Bare "one" is deliberately excluded — it matches half of all headlines.)
// ── Panels ────────────────────────────────────────────────────────────────
function CoveragePanel({ articles }: { articles: Article[] }) {
  if (!articles.length) {
    return <p className="rounded-xl border border-ink-700 bg-ink-900 p-4 text-sm text-fog">No coverage connected for this event yet.</p>;
  }
  // Reddit-style: grouped by topic with a heading + count per bucket.
  const groups = groupCoverage(articles);
  return (
    <div className="flex flex-col gap-5">
      {groups.map((g) => (
        <section key={g.key}>
          <div className="mb-2 flex items-center gap-2">
            {(() => { const Icon = COVERAGE_ICON[g.key] ?? Newspaper; return <Icon className="size-4 text-fog" aria-hidden />; })()}
            <h3 className="font-display text-sm font-bold uppercase tracking-wide text-chalk">{g.label}</h3>
            <span className="rounded-full bg-ink-800 px-2 py-0.5 text-[10px] font-semibold tabular-nums text-fog">
              {g.articles.length}
            </span>
          </div>
          <div className="flex flex-col gap-2">
            {g.articles.map((a) => (
              <Link
                key={a.id}
                href={`/news/${a.slug}`}
                className="flex items-center gap-3 rounded-xl border border-ink-700 bg-ink-900 p-3 transition-all hover:-translate-y-0.5 hover:border-blood-500/40"
              >
                <div className="relative size-14 shrink-0 overflow-hidden rounded-lg bg-ink-800">
                  {/* Real cover when the feed gives one (via /api/img), else locally
                      generated category art — never a torn/blank tile. */}
                  <Image src={safeNewsCover(a.slug, a.coverImageUrl)} alt="" fill className="object-cover" sizes="56px" unoptimized />
                </div>
                <div className="min-w-0 flex-1">
                  <h4 className="line-clamp-2 text-sm font-semibold leading-snug text-chalk">{a.title}</h4>
                  <p className="mt-0.5 text-[11px] text-fog">
                    {[a.author, formatDate(a.publishedAt, { month: "short", day: "numeric" })].filter(Boolean).join(" · ")}
                  </p>
                </div>
                <ArrowRight className="size-4 shrink-0 text-fog" />
              </Link>
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}

// Reads the database at runtime — never statically prerendered at build.
export const dynamic = "force-dynamic";
