import { getSessionUserId } from "@/lib/auth";

// ════════════════════════════════════════════════════════════════════════════
//  Who is this feed request for?
//
//  ── H-2: what this used to do, and why it was exploitable ─────────────────
//  It was:
//
//      const uid = await getSessionUserId();
//      return uid ?? fallbackCid;          // ← the caller picks their own key
//
//  For a signed-in request that is correct: the session wins and a supplied
//  `cid` is ignored. For an ANONYMOUS request the caller's `cid` — read
//  straight off the query string or JSON body — became the storage key
//  verbatim. And `User.id` is not a secret: the public leaderboard serves cuid
//  values next to usernames in its RSC payload.
//
//  So an unauthenticated attacker could read an id off a public page and then
//  address that person's personalisation namespace directly:
//
//      GET  /api/feed/library?cid=<their id>     → their saved collections
//      POST /api/feed/prefs   {"cid":"<their id>"} → writes to their prefs
//
//  Both were confirmed against production with a synthetic key. Feed state, not
//  documents — but unauthenticated, read AND write, aimed at a named person.
//
//  ── The fix: two namespaces that cannot collide ───────────────────────────
//  Authenticated identity stays the RAW session user id. That is deliberate:
//  it is what `following.ts` and `home/recommendations.ts` already write
//  directly via `dbPersistServed(userId, …)`, and leaving it unchanged means no
//  signed-in user loses a row.
//
//  Anonymous identity is ALWAYS prefixed. A caller-supplied value can therefore
//  never equal a `User.id`, whatever they send — the impersonation is not
//  blocked by a check, it is unrepresentable.
//
//  ── Why there is no compatibility fallback ────────────────────────────────
//  Existing anonymous rows are keyed by a bare `cid`, so they become
//  unreachable and logged-out personalisation resets once. Reading through to
//  the bare key when the namespaced one is empty would restore that data AND
//  reopen the vulnerability exactly: an attacker sends `cid=<victim user id>`,
//  the namespaced lookup misses, the fallback hits the victim's rows. The
//  reset is the cheaper mistake, and it only affects signed-out browsers'
//  recommendation state.
// ════════════════════════════════════════════════════════════════════════════

/** Prefix for every non-authenticated identity. Never a valid `User.id`. */
const ANON_PREFIX = "anon:";

/**
 * The shared bucket for callers who send nothing usable.
 *
 * Pre-existing behaviour — `cid || "anon"` at every call site meant a missing
 * id already collapsed to one shared row space. Kept, but now inside the
 * anonymous namespace where it cannot reach a user's rows.
 */
const ANON_FALLBACK = `${ANON_PREFIX}shared`;

/**
 * Client ids are generated by `components/feed/client.ts` as
 * `c_<base36 random><base36 timestamp>`. Anything outside this shape is not
 * something this application produced, so it is collapsed to the shared bucket
 * rather than trusted — that bounds how many distinct row-spaces an attacker
 * can create by inventing ids, and keeps the column length predictable.
 */
const CID_OK = /^[A-Za-z0-9_-]{4,64}$/;

/**
 * Resolve the storage identity for a feed request.
 *
 * THE ONLY path feed persistence may use to turn a request into a key. A route
 * that reads `cid` and passes it anywhere else has reintroduced H-2; the
 * feed-identity test asserts no route does.
 */
export async function feedKey(fallbackCid: string | undefined | null): Promise<string> {
  let uid: string | null = null;
  try {
    uid = await getSessionUserId();
  } catch {
    // A broken session resolves to ANONYMOUS, never to the caller's own claim.
    // The old code returned `fallbackCid` here, so a request that could induce
    // a session error got to name its own identity — the same hole by a second
    // route.
    uid = null;
  }
  if (uid) return uid;
  return anonKey(fallbackCid);
}

/** Namespace a client-supplied id. Exported for tests and for direct callers. */
export function anonKey(cid: string | undefined | null): string {
  if (!cid) return ANON_FALLBACK;

  // Strip an existing prefix FIRST, then validate the bare id. Order matters:
  // `CID_OK` excludes `:`, so validating before stripping would reject every
  // already-namespaced value — a client echoing back a key it was handed would
  // silently land in the shared bucket, and the un-double-prefix branch would
  // be dead code.
  const trimmed = cid.trim();
  const bare = trimmed.startsWith(ANON_PREFIX) ? trimmed.slice(ANON_PREFIX.length) : trimmed;

  if (!CID_OK.test(bare)) return ANON_FALLBACK;
  return ANON_PREFIX + bare;
}

/** True when a key belongs to the anonymous namespace. */
export function isAnonKey(key: string): boolean {
  return key.startsWith(ANON_PREFIX);
}
