// ⚠️  AUTO-GENERATED by `scripts/ingest-federations.ts` — DO NOT EDIT BY HAND.
//
// Run `npm run ingest:federations` (with network access) to (re)populate this
// file from the official member directories. Until then it is intentionally
// empty — the registry shows the international governing bodies as the spine
// and grows nationals from this file once ingested.

import type { NationalFederation } from "./registry";

export const NATIONAL_FEDERATIONS: NationalFederation[] = [];

/** ISO timestamp of the last successful ingest run, or null if never run. */
export const FEDERATIONS_FETCHED_AT: string | null = null;
